export const LOADING_STATE = {
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED"
};

export const WORDS = {
  LOAD_REQUEST: "LOAD_REQUEST",
  LOAD_SUCCESS: "LOAD_SUCCESS",
  LOAD_FAILED: "LOAD_FAILED"
};
